apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
        - name: testapp
          image: shestera/scaletestapp
          resources:
            limits:
              memory: "30Mi"
            requests:
              memory: "20Mi"
          ports:
            - containerPort: 8080